Refactor/ccm 40 typescript
lmc-eu/cookie-consent-manager pull request #100
Opened 2021-11-29 10:00 UTC by literat

Migration of codebase to Typescript.

2021-11-29 11:18 UTC, literat commented on src/LmcCookieConsentManager.ts
> +type Args = {
Should we remove jsDoc comments and add them to this type?

2021-11-29 11:19 UTC, literat commented on src/init.ts
> +  // @ts-expect-error Element implicitly has an 'any' type because index expression is not of type 'number'.
Do not know how to type this, yet.

2021-11-29 11:22 UTC, literat commented
- [ ] Migrate tests to Typescript
- [ ] Migrate scripts to Typescript

2021-11-29 20:05 UTC, adamkudrna commented on src/LmcCookieConsentManager.ts
>  /* eslint-disable no-unused-vars */
Why so? 🤔  Isn't it worth a comment?

2021-11-30 10:47 UTC, literat commented on src/LmcCookieConsentManager.ts
>  /* eslint-disable no-unused-vars */
My bad. It belongs to line 36, which is default for onAcceptCallback. It respects interface but returns nothing.

2021-12-02 12:41 UTC, literat commented on src/LmcCookieConsentManager.ts
> +type Args = {
Ok, refactored comments and moved them to types definition.

2021-12-09 15:04 UTC, OndraM requested changes

2021-12-09 15:04 UTC, OndraM commented on src/types/CookieConsent.ts
> +  getConfig: (name: string) => any;
Not sure which of the internal methods we should describe here, but at least `allowedCategory`  and `eraseCookies` (see [docs](https://github.com/orestbida/cookieconsent#api--configuration-parameters)) could be added, because we expect them to be called by the library users.

2021-12-10 09:44 UTC, literat commented on package.json
> +    "@typescript-eslint/parser": "^5.4.0",
Fixed.

2021-12-10 09:44 UTC, literat commented on package.json
> +    "typescript": "^4.5.2"
Fixed.

2021-12-10 09:45 UTC, literat commented on package.json
> +    "typescript": "^4.5.2"
Fixed.

2021-12-10 09:59 UTC, OndraM commented on src/LmcCookieConsentManager.ts
> +const defaultAcceptCallback: OnAcceptCallback = (cookie, cookieConsent) => {};
I'm still thinking about this name... For me, the name suggest there is some "default" callback, ie. containing some default logics. While the default callback is just empty.

What about something like `const noopCallback`? `noop` seems like a common name for such functions - dating back [to jQuery](https://api.jquery.com/jquery.noop/)... What do you think?

2021-12-10 10:01 UTC, literat commented on src/LmcCookieConsentManager.ts
>    }
Yes, we must stay with this check. Typescript helps you only with untranspiled code. But when the code is transpiled and used via CDN the type safety that typescript gives you is missing.

2021-12-10 10:05 UTC, literat commented on src/LmcCookieConsentManager.ts
> +const defaultAcceptCallback: OnAcceptCallback = (cookie, cookieConsent) => {};
Renamed.

2021-12-10 10:06 UTC, literat commented on src/LmcCookieConsentManager.ts
> +const LmcCookieConsentManager: CookieConsentManager = (serviceName, args) => {
I have returned the jsdoc comments. Please try it again and let me know if this helped.

2021-12-10 10:08 UTC, literat commented on src/consentCollector.ts
> +async function postDataToApi(apiUrl: string, payload: any): Promise<string> {
Thanks, you are right. Fixed.

2021-12-10 10:51 UTC, literat commented on src/languages/cs.ts
> +export const config = (messages: Messages) => {
Good point. Renamed and also refactored entire language configs.

2021-12-10 11:08 UTC, literat commented on src/types/CookieConsent.ts
> +  getConfig: (name: string) => any;
Ok, I've added them.

2021-12-10 11:09 UTC, literat commented on src/types/CookieConsent.ts
> +export enum CookieConsentLevel {
I have separated types of orest bida cookie consent and our cookie consent manager. Do you think it is better now or should we name the files better?

2021-12-12 15:22 UTC, OndraM commented on src/LmcCookieConsentManager.ts
>    }
Yes, but we don't do similar type assertions on all the other parameters... 🤷

But ok, lets keep it there.

2021-12-12 16:21 UTC, OndraM requested changes

2021-12-12 16:21 UTC, OndraM commented on src/LmcCookieConsentManager.ts
> +const LmcCookieConsentManager: CookieConsentManager = (serviceName, args) => {
No really :-( 

Compare Ctrl+Q (quick documentation) in PhpStrom in current main branch:
![obrazek](https://user-images.githubusercontent.com/793041/145719633-cabe1207-844d-4dfc-b74f-595c9cf2205f.png)

And current built version:
![obrazek](https://user-images.githubusercontent.com/793041/145719660-7152d126-22c1-481b-a051-5b564556e1c3.png)

Not sure what is the issue there. Seems like phpstorm does not associate `build/init.js` with `build/init.d.ts` 🤔

2021-12-13 07:02 UTC, literat commented on src/LmcCookieConsentManager.ts
>    }
For all other parameter we have defaults which is merged with options provided by developer. So they should be never `undefined` but it can be provided inappropriate type of option in CDN variant. 🤷‍♂️

2021-12-13 10:17 UTC, literat commented on src/types/CookieConsent.ts
> +export enum CookieConsentLevel {
So we want to distinguish between `vanilla-cookieconsent` and our types. So there should be maybe two files with types or even `vanilla-cookieconsent.d.ts`  with declared types for Orest Bida's library.

2021-12-13 10:18 UTC, literat commented on src/languages/settingsModalBlocks.ts
> +export const blocks = [
You are right. I did not notice that this would be problem in future. I've reverted this and keep blocks in language files.

2021-12-14 07:59 UTC, literat commented on src/LmcCookieConsentManager.ts
> +type Args = {
We should solve this in separate PR.

2021-12-14 07:59 UTC, literat commented on src/LmcCookieConsentManager.ts
> +const LmcCookieConsentManager: CookieConsentManager = (serviceName, args) => {
We should solve this in separate PR.

2021-12-14 08:02 UTC, literat commented
@OndraM Please do an one last look and we should merge this.

2021-12-14 11:08 UTC, OndraM approved these changes
:1st_place_medal: 

Could you please rebase and squash, but please wait with the merge until we solve the CommonJS issue? We may need to do 1.0.2 release before merging this...

2021-12-15 00:17 UTC, OndraM commented
:information_source: Ready to merge. I will merge it tomorrow, once we get confirmation 1.0.3 fixes the crypto-issue.

2021-12-15 13:36 UTC, merged