Chore: Introduce publish package pipeline #CCM-8
lmc-eu/cookie-consent-manager pull request #16
Opened 2021-10-22 08:29 UTC by literat

* based on release publishing

2021-11-01 11:49 UTC, literat commented
@OndraM Updated work flow to trigger it localy with `yarn release`, than check it and push. After that publish pipeline will be running by gh actions.

2021-11-01 15:53 UTC, OndraM requested changes
It looks nice 👍

Could you also please document the release workflow into README? Maybe add new "Create new release"  section as part of [Development and contributing](https://github.com/lmc-eu/cookie-consent-manager/#development-and-contributing) section.

2021-11-01 15:53 UTC, OndraM commented on package.json
> +    "version": "git status && git add CHANGELOG.md package.json ./dist && git status",
So if it re-uses the name of native [`yarn version`](https://classic.yarnpkg.com/en/docs/cli/version), it is run as part of it? Is it usual to override names of the native scripts like this? It confused me on first look 👀

2021-11-01 15:53 UTC, OndraM commented on .github/workflows/publish.yaml
> +          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
Why is this step needed? Isn't the following `yarn publish` enough? (It also receives `NPM_TOKEN`, so it is a bit confusing why it is needed for two steps).

2021-11-01 15:53 UTC, OndraM commented on package.json
> +    "version": "git status && git add CHANGELOG.md package.json ./dist && git status",
BTW isn't the changelog generation missing from the script? There is `git add CHANGELOG.md`, though none changelog is generated when running `yarn release`.

2021-11-01 15:53 UTC, OndraM commented on bin/ci/semver.sh
> +    local commits=$(git log --oneline $(git describe --tags --abbrev=0 @^)..@ --grep="$1" 2> /dev/null)
```suggestion
    local commits
    commits=$(git log --oneline "$(git describe --tags --abbrev=0 @^)"..@ --grep="$1" 2> /dev/null)
```

https://github.com/koalaman/shellcheck/wiki/SC2155#problematic-code-in-the-case-of-local

2021-11-01 15:53 UTC, OndraM commented on bin/ci/semver.sh
> +    if [ $? -eq 128 ]; then
Could you please add comment what does comparing with 128 mean? It looks a bit cryptic :)

2021-11-01 15:53 UTC, OndraM commented on bin/ci/semver.sh
> +    then
```suggestion
    elif [ -z "$commits" ]; then
```

2021-11-01 15:53 UTC, OndraM commented on bin/ci/semver.sh
> +    then
```suggestion
    elif [ $(grep_word_from_git_commits_since_last_tag "Feat") -gt 0 ]; then
```

2021-11-01 15:53 UTC, OndraM commented on bin/ci/semver.sh
> +    then
```suggestion
    if [ "$(grep_word_from_git_commits_since_last_tag "BREAKING CHANGE")" -gt 0 ]; then
```
https://github.com/koalaman/shellcheck/wiki/SC2006
https://github.com/koalaman/shellcheck/wiki/SC2046

2021-11-01 20:58 UTC, literat commented on package.json
> +    "version": "git status && git add CHANGELOG.md package.json ./dist && git status",
Yes, the changelog command is missing. Thanks for notice.

2021-11-01 21:00 UTC, literat commented on package.json
> +    "version": "git status && git add CHANGELOG.md package.json ./dist && git status",
What do you mean with "re-uses" of the name? `pre` and `post` are standard prefixes and postfixes for running scripts before and after main script (https://docs.npmjs.com/cli/v7/using-npm/scripts#pre--post-scripts).

2021-11-01 21:03 UTC, literat commented on bin/ci/semver.sh
> +    if [ $? -eq 128 ]; then
Comment added.

2021-11-01 21:03 UTC, literat commented on bin/ci/semver.sh
> +    local commits=$(git log --oneline $(git describe --tags --abbrev=0 @^)..@ --grep="$1" 2> /dev/null)
Fixed, thanks.

2021-11-01 21:04 UTC, OndraM commented on package.json
> +    "version": "git status && git add CHANGELOG.md package.json ./dist && git status",
I meant the `version` script itself, not the pre/post ones. Because there is already the native `yarn version` and here you are defining your own as an addition.

2021-11-01 21:08 UTC, literat commented on package.json
> +    "version": "git status && git add CHANGELOG.md package.json ./dist && git status",
No, this is same as `npm version`, see https://classic.yarnpkg.com/en/docs/cli/version. To get the version of yarn itself you must use `yarn --version`.

And of course with version command you can specify what should be done before committing and tagging (https://docs.npmjs.com/cli/v7/commands/npm-version#description).

2021-11-01 21:11 UTC, OndraM commented on bin/ci/semver.sh
> +    if [ $? -eq 128 ]; then
I though the "meaning" of this condition - the reason, why it is there. When does this condition happen in this scenario? Why is this some specific condition for exit code 128? Why not compare with other error codes? So some comment explaining this, because from reading the script I don't understand why is there such condition.

2021-11-01 21:11 UTC, literat commented
> It looks nice 👍
> 
> Could you also please document the release workflow into README? Maybe add new "Create new release" section as part of [Development and contributing](https://github.com/lmc-eu/cookie-consent-manager/#development-and-contributing) section.

Should I use CONTRIBUTING.md instead (https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)? And add that part from readme to it as well?

2021-11-01 21:17 UTC, OndraM commented on package.json
> +    "version": "git status && git add CHANGELOG.md package.json ./dist && git status",
I didn't meant `--version` :) . But the npm docs provides an answer:

> Run the `version` script. These scripts have access to the new version in package.json (so they can incorporate it into file headers in generated files for example). Again, scripts should explicitly add generated files to the commit using git add.

This is something not explained in yarn documentation, even in the examples there is just preversion/postversion. But if its the same as in npm, I understand its purpose,  thanks.

2021-11-01 21:20 UTC, literat commented on package.json
> +    "version": "git status && git add CHANGELOG.md package.json ./dist && git status",
Ok, now I understand your confusion :-)

2021-11-01 21:21 UTC, OndraM commented
> Should I use CONTRIBUTING.md instead (https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)? And add that part from readme to it as well?

I would now not bother with CONTRIBUTING.md for this project - we don't expect much external contributions... For now I think just short mention in readme would be enough. We can split it eventually later, if the readme become too long... (also this could be done in different PR, to not further extend scope of this one).

2021-11-02 00:25 UTC, OndraM requested changes

2021-11-02 00:25 UTC, OndraM commented on package.json
> +    "version": "yarn changelog && git status && git add CHANGELOG.md package.json ./dist && git status",
Also, the `dist/` files build in preversion should be added.

2021-11-02 07:12 UTC, literat commented on package.json
> +    "version": "yarn changelog && git status && git add CHANGELOG.md package.json ./dist && git status",
They are there with `./dist` I presume.

2021-11-02 07:27 UTC, literat commented on bin/ci/semver.sh
> +    if [ $? -eq 128 ]; then
This is check for unpredictable behaviour. There are multiple commands in one and every single one could cause an error. So I have normalized the error status code to 2 when some unpredictable situation happend.

2021-11-02 07:51 UTC, literat commented on .github/workflows/publish.yaml
> +          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
`npm-auth` is creating `.npmrc` file with authentification configuration, sets right token and right registry. We can also omit this script and use `actions/setup-node@v2` with some configuration to do that for us (https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry).

But I want do that myself and also check the user with `npm whoami ` (https://docs.npmjs.com/cli/v7/commands/npm-whoami).

For publishing you need the token as well. So that is the reason why it is twice here.

Should I omit that script or add some comments to explain that?

2021-11-02 09:26 UTC, OndraM commented on package.json
> +    "version": "yarn changelog && git status && git add CHANGELOG.md package.json ./dist && git status",
But they were not added to the repo as part of the last release: https://github.com/lmc-eu/cookie-consent-manager/tree/main/dist

2021-11-02 09:50 UTC, literat commented on package.json
> +    "version": "yarn changelog && git status && git add CHANGELOG.md package.json ./dist && git status",
I do not understand what is wrong here. Could you be more specific, please?

2021-11-02 09:54 UTC, OndraM commented on package.json
> +    "version": "yarn changelog && git status && git add CHANGELOG.md package.json ./dist && git status",
I thought that as part of the release, new version of dist files should be build and added to the repository.

However - you tagged the 0.2.0 version, but the [files in dist](https://github.com/lmc-eu/cookie-consent-manager/tree/main/dist) are unchanged.

2021-11-02 10:10 UTC, literat commented on package.json
> +    "version": "yarn changelog && git status && git add CHANGELOG.md package.json ./dist && git status",
Oh, now I see the problem. My bad, I am sorry. However in the package itself they are modified. So this is problem only for examples of the 0.2.0 version. This release should fix it.

2021-11-02 10:37 UTC, OndraM commented on package.json
> +    "version": "yarn changelog && git status && git add CHANGELOG.md package.json ./dist && git status",
Ok, we will see.

![EYEgxfLXsAAItE9](https://user-images.githubusercontent.com/793041/139831263-6c595620-cce5-4ee5-acce-38144dbc1242.jpg)

2021-11-02 10:39 UTC, OndraM commented on bin/ci/semver.sh
> +    if [ $? -eq 128 ]; then
So if this is not specific to exit code 128 but generally "command caused an error", why not to check whether return code does not equal 0?

2021-11-02 11:47 UTC, literat commented on bin/ci/semver.sh
> +    if [ $? -eq 128 ]; then
So what do you suggest? Because this is working script and we spend a lot of time on this single detail. Maybe simple
```bash
if [ -z "$commits" ]; then
        echo 0
    else
        echo 1
    fi
```

is enough?

2021-11-02 11:50 UTC, OndraM commented on bin/ci/semver.sh
> +    if [ $? -eq 128 ]; then
Well if the purpose of the condition is to check whether the git command has not failed, then:

```diff
-     if [ $? -eq 128 ]; then 
+     if [ $? -ne 0 ]; then  
```

I thought there was some hidden meaning why check specifically the128 exit code, thus my confusion.

2021-11-02 11:52 UTC, literat commented on bin/ci/semver.sh
> +    if [ $? -eq 128 ]; then
Ok, fixed.

2021-11-02 11:53 UTC, OndraM commented on .github/workflows/publish.yaml
> +          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
No, this is fine, thanks for explanation 👍

2021-11-02 11:54 UTC, OndraM approved these changes
LGTM! :ship: 

(Also, could you please do a new release 0.3.0 right after this is merged?)

2021-11-02 12:04 UTC, merged