Feat: Make texts for cs, en, sk and pl less formal #CCM-50
lmc-eu/cookie-consent-manager pull request #166
Opened 2021-12-17 01:22 UTC by OndraM

2021-12-17 13:24 UTC, literat requested changes

2021-12-17 13:24 UTC, literat commented on src/languages/cs.ts
> +      )} s využíváním souborů Cookies na účely personalizace, analýzy a cíleného marketingu.
I am missing a czech word `souhlas` here.

2021-12-17 13:24 UTC, literat commented on src/languages/__tests__/__snapshots__/langConfig.test.ts.snap
> +      Kliknutím na tlačítko „Přijmout všechny“ dáte společnostem test1, test2 a test3 s využíváním souborů Cookies na účely personalizace, analýzy a cíleného marketingu.
In this snapshot the word `souhlas` is also missing.

2021-12-19 17:46 UTC, OndraM commented on src/languages/__tests__/__snapshots__/langConfig.test.ts.snap
> +      Kliknutím na tlačítko „Přijmout všechny“ dáte společnostem test1, test2 a test3 s využíváním souborů Cookies na účely personalizace, analýzy a cíleného marketingu.
Nice catch! Fixed.

2021-12-20 14:47 UTC, merged