Chore: Trigger deploy preview only when certain directories changed
lmc-eu/cookie-consent-manager pull request #169
Opened 2021-12-17 16:16 UTC by literat

* using custom netlify build hook
  * @see https://docs.netlify.com/configure-builds/build-hooks/

2021-12-22 11:41 UTC, OndraM requested changes
BTW, is the shell script even necessary? Cannot the same be accomplished right in action config? Like:

```yaml
on:
  push:
    paths:
      - 'src/'
      - 'examples/'
```

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-including-paths

2021-12-22 11:41 UTC, OndraM commented on bin/ci/deploy-preview.sh
> +  git fetch --no-tags --depth=50 origin main
Whats the purpose of this fetch? If we need depth > 1 (which is `actions/checkout@v2` default), we can use `fetch-depth: 50` right in the build step, see https://github.com/actions/checkout/

2021-12-22 11:41 UTC, OndraM commented on bin/ci/deploy-preview.sh
> +  curl -X POST -d '{}' https://api.netlify.com/build_hooks/61bca39f3b89823193476ecd?trigger_branch=$1
Don't you want to put the hook id to secrets? 🤔

2022-04-22 13:16 UTC, literat commented
Closing this because we are deploying under the LMC account from now.

2022-04-22 13:16 UTC, closed without merging