Docs: Add example to show all supported languages
lmc-eu/cookie-consent-manager pull request #172
Opened 2021-12-20 10:33 UTC by OndraM

Just an quick proof of concept so that we have a place to show and test all languages.

2021-12-20 10:44 UTC, OndraM commented
Manually deployed this branch here: https://lmc-eu.github.io/cookie-consent-manager/examples/languages.html

2021-12-20 13:19 UTC, literat commented
@OndraM Cookie reset button is somehow missing.

2021-12-20 13:20 UTC, literat requested changes
Cookie reset button is somehow missing.

2021-12-21 11:25 UTC, literat approved these changes

2021-12-21 11:34 UTC, merged