Feat: Add settings modal translations for all remaining languages
lmc-eu/cookie-consent-manager pull request #183
Opened 2022-01-14 23:22 UTC by OndraM

2022-01-17 06:17 UTC, literat commented
I have a problem with some wording because it sounds weird to me. Like in English `your own settings`. Or Czech or Slovak `vlastní nastavení`. There is nothing mine on a webpage unless I have access to some kind of an admin panel. So maybe `in the settings` is better, or `in the custom settings`.

We can use `Nastavení cookies` in Czech instead of `Vlastní nastavení` because I think it is not a correct translation of a `custom settings`, maybe `podrobné nastavení`. Maybe the same in other languages.

What do you think?

2022-01-17 06:17 UTC, literat requested changes

2022-01-17 06:17 UTC, literat commented on src/languages/de.ts
> +          title: 'Marketing-Cookies',
`Marketing-Cookies` -> `Marketing Cookies` ?

2022-01-17 11:25 UTC, OndraM commented
> What do you think?

This would have to be discussed elsewhere - this is just an implementation of CCM-55 .

2022-01-20 14:18 UTC, OndraM commented on src/languages/de.ts
> +          title: 'Marketing-Cookies',
Updated

2022-01-20 14:19 UTC, OndraM commented
@literat Translations updated.

2022-01-20 20:22 UTC, literat approved these changes

2022-01-24 12:14 UTC, merged