Refactor/ccm 48 callbacks
lmc-eu/cookie-consent-manager pull request #188
Opened 2022-01-20 21:52 UTC by literat

2022-01-25 12:15 UTC, OndraM requested changes

2022-02-02 14:26 UTC, literat commented on README.md
> +| `onFirstAction`           | Right after all cookies are accepted                                                                                      |
Changed.

2022-02-02 14:27 UTC, literat commented on README.md
> +| `onChange` | Right after user change his/her preferences                                                          |
Fixed.

2022-02-02 15:08 UTC, literat commented on src/types/CookieConsentManager.ts
> +type Callback = (cookieConsent: VanillaCookieConsent.CookieConsent<CookieConsentCategory>) => void;
Developer's WET dreams are coming :D

2022-02-02 15:08 UTC, literat commented on src/types/CookieConsentManager.ts
> +type Callback = (cookieConsent: VanillaCookieConsent.CookieConsent<CookieConsentCategory>) => void;
Did not know about this 👍  But in most cases I will stay with DRY ;-)

2022-02-02 15:19 UTC, literat commented on src/LmcCookieConsentManager.ts
> + */
Added somehow by IDE. I'll fix it.

2022-02-03 15:16 UTC, OndraM approved these changes

2022-02-07 06:32 UTC, merged