Style settings modal according to graphic design
lmc-eu/cookie-consent-manager pull request #197
Opened 2022-01-25 23:38 UTC by adamkudrna

- **BC:** Increase hierarchy of link button in consent modal to secondary button
- Style settings modal
- Add two dozens of new CSS custom properties
- Support all UI options of the vanilla library
- Update Spirit Design Tokens
- Organise styles into multiple directories and SCSS files to improve maintainability
- Watch and build SCSS during development

## Consent Bar

<img width="1100" alt="obrazek" src="https://user-images.githubusercontent.com/5614085/151077368-d2c3dee2-6082-4508-808a-f0baf94cff83.png">

![Snímek obrazovky 2022-01-26 v 00 32 26](https://user-images.githubusercontent.com/5614085/151077434-b0e48dab-0c7f-4c44-81d9-c1582d1beee0.png)

## Settings Modal

<img width="840" alt="obrazek" src="https://user-images.githubusercontent.com/5614085/151077172-77c34971-4965-40a3-a93f-68ece2438877.png">

![Snímek obrazovky 2022-01-26 v 00 31 09](https://user-images.githubusercontent.com/5614085/151077238-b8b9970e-d93a-4e61-980e-0a8898671fa1.png)

![Snímek obrazovky 2022-01-26 v 00 37 01](https://user-images.githubusercontent.com/5614085/151077770-90549f6a-f9b5-460e-bf5e-af6265cb84c3.png)

![Snímek obrazovky 2022-01-26 v 00 36 45](https://user-images.githubusercontent.com/5614085/151077783-4a51f7f8-9930-4f4f-97e4-04b089447b03.png)

2022-01-26 12:18 UTC, OndraM commented
Don't forget on this please :) 

- [ ] Add upgrade howto (description of the BC breaks and how to upgrade)

2022-01-26 12:24 UTC, OndraM requested changes
I added task to the issue description, so please don't forget about it :).

Also the window width (maybe the height as well) would probably need to be enlarged. It don't fit in many languages.
![obrazek](https://user-images.githubusercontent.com/793041/151162443-68bf944d-7049-4672-b703-2725eeb2800f.png)

Try yourself: https://lmc-eu.github.io/cookie-consent-manager/examples/languages.html

2022-01-26 12:24 UTC, OndraM commented on src/LmcCookieConsentManager.scss
> + * Copyright 2021–2022 LMC s.r.o.
🙈

2022-01-27 17:19 UTC, adamkudrna commented on package.json
> +    "watch:css": "nodemon --watch src/scss/ --ext scss --exec \"yarn css\""
Right, I just wasn't brave enough to touch the `serve` script.

2022-01-27 18:15 UTC, adamkudrna commented on package.json
> +    "watch:css": "nodemon --watch src/scss/ --ext scss --exec \"yarn css\""
BTW can we (even now) add a task to watch also TS files for changes? Now I have to run `yarn build` everytime I make a change in TS (I'm playing around with the config a lot).

2022-01-28 13:36 UTC, OndraM commented on package.json
> +    "watch:css": "nodemon --watch src/scss/ --ext scss --exec \"yarn css\""
Yes, but I suggest separating all build-realted changes to a separate pull-request targeted to the main brach.

2022-01-28 13:38 UTC, OndraM requested changes
As noted, please remove the build-realted changes (ie. all script changes in package.json, nodemon dependency) to some other pull request , as this is not related to the scope of the issue itself.

2022-01-28 16:47 UTC, adamkudrna commented on package.json
> +    "watch:css": "nodemon --watch src/scss/ --ext scss --exec \"yarn css\""
OK, moved to PR #199.

2022-01-28 18:43 UTC, adamkudrna commented on package.json
> +    "start": "npm-run-all --parallel serve watch:css",
Change moved to PR #199.

2022-01-30 22:50 UTC, OndraM requested changes
Nice 👍. Could you have a look at those two issues please?

2022-01-30 22:50 UTC, OndraM commented on README.md
> +```
I suggest removing this section altogether. AFAIK no-one actually uses it, so lets make the readme shorter, we don't need to cover all not-implemented but possible features...

2022-01-30 22:50 UTC, OndraM commented on src/scss/style/_settings-modal.scss
> +        background-color: currentColor;
When I try to integrate this with new version of stylelint (#195), this complains:

```
> $ stylelint --config .stylelintrc "src/**/*.scss" "examples/assets/*.css" --cache --cache-location .cache/.stylelintcache

src/scss/style/_settings-modal.scss
 92:27  ✖  Expected "currentColor" to be "currentcolor"  value-keyword-case
```

It seems there is maybe a change from `currentColor`  in[CSS Color Level 3](https://www.w3.org/TR/css-color-3/#currentcolor) to `currentcolor` [Level 4](https://www.w3.org/TR/css-color-4/#currentcolor-color)?

Related stylelint issues: https://github.com/stylelint/stylelint/issues/4884, https://github.com/stylelint/stylelint/pull/5849, https://github.com/stylelint/stylelint/issues/5863

@adamkudrna Could you please have a look and say what should we be using and how to configure stylelint? And if it will be kept as-is, we would need to update the stylelint config.

2022-01-30 22:55 UTC, OndraM commented
BTW, as a result of the refactoring, all those files are now built to `dist/scss/`, so they should all be part of dist folder, is this expected? ([Compare with current state](https://github.com/lmc-eu/cookie-consent-manager/tree/main/dist/scss).)

```
dist/scss/
├── index.scss
├── settings
│   └── _settings.scss
├── style
│   ├── _buttons.scss
│   ├── _consent-modal.scss
│   ├── _links.scss
│   ├── _main.scss
│   ├── _settings-modal.scss
│   ├── _toggles.scss
│   └── _typography.scss
├── theme
│   ├── _default.scss
│   └── _vanilla.scss
└── tools
    └── _units.scss
```

2022-01-31 11:21 UTC, adamkudrna commented
> BTW, as a result of the refactoring, all those files are now built to `dist/scss/`, so they should all be part of dist folder, is this expected? ([Compare with current state](https://github.com/lmc-eu/cookie-consent-manager/tree/main/dist/scss).)

Yes, it's correct. Sass source is intended for use with Spirit so it can be compiled with custom colors etc.

2022-01-31 11:37 UTC, adamkudrna commented on src/scss/style/_settings-modal.scss
> +        background-color: currentColor;
@OndraM Please change `currentColor` to `currentcolor` as the former is now considered legacy. I cannot do it here without upgrading to Stylelint 14.3.

2022-01-31 11:38 UTC, adamkudrna commented
> Nice 👍. Could you have a look at those two issues please?

Fixed and ⚠️ REBASED ⚠️.

2022-01-31 12:16 UTC, literat approved these changes

2022-01-31 12:34 UTC, OndraM approved these changes
🎉

2022-01-31 12:36 UTC, merged