Docs: Add upgrade guide
lmc-eu/cookie-consent-manager pull request #203
Opened 2022-02-04 20:21 UTC by OndraM

Should include guide for applying following changes:
- [x]  CSS changes #197 
- [x]  `DOMContentLoaded` recommendation #202
- [ ] Callback refactoring #188

2022-02-07 06:45 UTC, literat requested changes

2022-02-07 06:45 UTC, literat commented on UPGRADE-2.0.md
> +## Use `DOMContentLoaded` event instead of `load`
Maybe adding a link to https://javascript.info/script-async-defer#defer will help to understand why we are doing this. :-)

2022-02-07 06:45 UTC, literat commented on UPGRADE-2.0.md
> +event does not wait for loading of other page resources (like images).
```suggestion
event does not wait for the loading of other page resources (like images).
```

2022-02-07 06:45 UTC, literat commented on UPGRADE-2.0.md
> +When loading the plugin from standalone file or from CDN, you should keep using the `defer` attribute of `<script>`.
```suggestion
When loading the plugin from a standalone file or CDN, you should keep using the `defer` attribute of `<script>`.
```

2022-02-07 06:45 UTC, literat commented on UPGRADE-2.0.md
> +**Secondary button** _(Accept necessary)_ in the consent bar is now rendered as button (previously rendered as link).
```suggestion
**Secondary button** _(Accept necessary)_ in the consent bar is now rendered as a button (previously rendered as a link).
```

2022-02-07 06:46 UTC, literat commented
> * [ ]  Callback refactoring [Refactor callbacks #CCM-48 #188](https://github.com/lmc-eu/cookie-consent-manager/pull/188)

Merged.

2022-02-08 11:37 UTC, OndraM commented
@literat Upgrade guide now includes the rearranged callbacks. I tried to covered most of the possible scenarios. But suggestion if something more should be added are welcomed (see JIRA for the [list of what teams are using now](current )).

2022-02-08 13:55 UTC, literat requested changes

2022-02-08 13:55 UTC, literat commented on README.md
> +Each configured callback receives `cookieConsent` parameter - instance of the underlying [cookie consent] library,
`[cookie consent]` probably missing link?

2022-02-08 13:55 UTC, literat commented on README.md
> +| `onFirstAccept(cookieConsent)`        | This function will be executed only once, when the user takes the first action (accept all/only some/only necessary categories).
```suggestion
| `onFirstAccept(cookieConsent)`        | This function will be executed only once, when the user takes the first action (accept all/only selected/only necessary categories).                                |
```

2022-02-08 13:55 UTC, literat commented on README.md
> +| `onChange(cookieConsent, categories)` | Right after user changes cookie settings. The callback receives also `categories` object containing arrays of `accepted`, `rejected`, and `changed` categorie
```suggestion
| `onChange(cookieConsent, categories)` | Right after the user changes cookie settings. The callback receives also `categories` object containing arrays of `accepted`, `rejected`, and `changed` categories. |
```

2022-02-08 13:55 UTC, literat commented on UPGRADE-2.0.md
> +- `onFirstAccept(cookieConsent)` – executed only once, when the user takes the first action. Don't forget that unlike in previous version, user can now allow **only some** categories. `onFirstAcceptA
```suggestion
- `onFirstAccept(cookieConsent)` – executed only once, when the user takes the first action. Don't forget that unlike in the previous version, users can now allow **only some** categories. `onFirstAcceptAll` and `onFirstAcceptOnlyNecessary` callbacks were removed and their logic should be handled inside this callback.
```

2022-02-08 13:55 UTC, literat commented on UPGRADE-2.0.md
> +- `onAccept(cookieConsent)` – any consent was detected (either given now or after page load if it was already saved previously). Don't forget that unlike in previous version, **only some** categories
```suggestion
- `onAccept(cookieConsent)` – any consent was detected (either given now or after page load if it was already saved previously). Don't forget that unlike in the previous version, **only some** categories could be allowed. `onAcceptAll` and `onAcceptOnlyNecessary` callbacks were removed and their logic should be handled inside this callback.
```

2022-02-10 11:52 UTC, literat approved these changes

2022-02-10 12:16 UTC, merged