Docs: Extend configuration example page to showcase onChange event
lmc-eu/cookie-consent-manager pull request #209
Opened 2022-02-10 13:07 UTC by OndraM

2022-02-10 14:19 UTC, literat requested changes

2022-02-10 14:19 UTC, literat commented on examples/configuration.html
> +                    <li>Clearing localStorage if user updates consent and rejects some consent category (<code>onChange</code>)</li>
This is the reaction to an event in time, so I think `when` sounds better in this case.

2022-02-10 17:28 UTC, OndraM commented on examples/configuration.html
> +                    <li>Clearing localStorage if user updates consent and rejects some consent category (<code>onChange</code>)</li>
Agreed, applied

2022-02-11 08:54 UTC, literat approved these changes

2022-02-11 10:06 UTC, merged