Fix/isolated modules
lmc-eu/cookie-consent-manager pull request #228
Opened 2022-03-21 12:59 UTC by literat

2022-03-21 13:21 UTC, OndraM commented on src/types/CookieConsentManager.ts
> +
The purpose of this is to workaround for not using enums, right?

So basically we will have to take care of variables which are basically "enums" in a two different ways, depending on whether the type is part of exported public API (so you must use generics like this, ie. emulate enum behavior) or whether they are used only internally (when you use "real" enums")? That is quite a confusing... 🤔

2022-03-21 13:34 UTC, literat commented on src/types/CookieConsentManager.ts
> +
Well, not so far confusing. This is not the first time I encounter some problem with enums. For example iterating over enum and getting values from them is a task from hell (search something like "how to use enum as index key type in typescript").

So my opinion is to ban enums for type safety reasons. Not just that we are developing a library but also for sake of our souls. It is better not to think about whether I am using enum internally or not. Just do not use them everywhere.

2022-03-23 12:05 UTC, literat commented
It has been confirmed that this is working solution.

2022-03-23 14:32 UTC, OndraM requested changes

2022-03-23 14:32 UTC, OndraM commented on examples/webpack-with-typescript/index.ts
> +      force_consent: true,
Please remove overriding force_consent from the examples... There is already the displayMode being used, so either use it as soft or force, but don't combine it with force_consent in the examples. :)

2022-03-23 15:05 UTC, literat commented on src/types/CookieConsentManager.ts
> +export type Values<T> = T[keyof T];
Here it is exported for internal use only. You must look at what is exported from the package main entry point which is `src/LmcCookieConsentManager.ts`

2022-03-23 15:07 UTC, literat commented on .github/workflows/build.yaml
> +name: Build
Renamed, sounds reasonable.

2022-03-23 15:07 UTC, literat commented on .github/workflows/build.yaml
> +    name: Build
Renamed.

2022-03-23 15:08 UTC, literat commented on examples/webpack-with-typescript/index.ts
> +      force_consent: true,
Removed.

2022-03-23 15:13 UTC, OndraM approved these changes

2022-03-23 15:22 UTC, merged