Feat: Enable management of third-party scripts
lmc-eu/cookie-consent-manager pull request #23
Opened 2021-10-30 12:22 UTC by OndraM

This adds default configuration to enable third-party script management:
```js
page_scripts: true, // Manage third-party scripts loaded using <script>
```

If someone won't use this feature, the overhead in the vanilla library is one call of `var scripts = document.querySelectorAll('script[' + _config.script_selector + ']');` on init. I guess this is acceptable performance tradeoff?

Other option would be leave this as default and add this the configurable parameters. What do you think?

2021-11-01 07:46 UTC, literat commented
> This adds default configuration to enable third-party script management:
> 
> ```js
> page_scripts: true, // Manage third-party scripts loaded using <script>
> ```
> 
> If someone won't use this feature, the overhead in the vanilla library is one call of `var scripts = document.querySelectorAll('script[' + _config.script_selector + ']');` on init. I guess this is acceptable performance tradeoff?
> 
> Other option would be leave this as default and add this the configurable parameters. What do you think?

I think that this is not as simple as you mean it. As I read in https://github.com/orestbida/cookieconsent#manage-third-party-scripts you must first update your script tags to `text/plain` with `data-` attribute. 

See https://github.com/orestbida/cookieconsent/blob/master/src/cookieconsent.js#L31 and https://github.com/orestbida/cookieconsent/blob/master/src/cookieconsent.js#L1261

So basically setting this option only to `true` will not work.

2021-11-01 07:47 UTC, literat requested changes

2021-11-01 07:47 UTC, literat commented on src/LmcCookieConsentManager.js
> +    page_scripts: true, // Manage third-party scripts loaded using <script>
Using only this option without modification of script tags will not work, see https://github.com/orestbida/cookieconsent#manage-third-party-scripts

2021-11-01 10:21 UTC, OndraM commented on src/LmcCookieConsentManager.js
> +    page_scripts: true, // Manage third-party scripts loaded using <script>
Sure, this will be documented in the readme, see #22: https://github.com/lmc-eu/cookie-consent-manager/pull/22/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R108

However without this option enabled it will not work even when product modifies the script tags. So the point is to make it enabled by default, and if the product decides to use this behavior, all they need to do is modify the script tags, as explained in the readme.

2021-11-01 11:11 UTC, literat commented on src/LmcCookieConsentManager.js
> +    page_scripts: true, // Manage third-party scripts loaded using <script>
I think that this is still misleading. If product want to manage third party cookie by cookie consent manager it must prepare those changes anyway. So it can also add another option to cookie consent manager.

You also wrote that product must provide at least one option in near future - https://github.com/lmc-eu/cookie-consent-manager/pull/22#issue-1039498802. So adding another one when it will want to manage third party cookie and also must update its script tags is not so much work.

Another handicap is that you are saying something like "hey, this options is on, so it will do something" but until you update script tags it will do nothing.

So my opinion is that we should leave it as is (false value) and the product developers must do those steps deliberatilly to make it work.

2021-11-01 20:41 UTC, literat approved these changes

2021-11-02 00:17 UTC, OndraM commented on src/LmcCookieConsentManager.js
> +    page_scripts: true, // Manage third-party scripts loaded using <script>
For now solved by adding documentation on how to disable the feature. Could be revisited lated.

2021-11-02 00:20 UTC, merged