Feat: Add secondaryButtonMode to choose secondary button behavior
lmc-eu/cookie-consent-manager pull request #234
Opened 2022-04-19 12:33 UTC by OndraM

#CCM-64

2022-04-20 07:26 UTC, literat requested changes

2022-04-20 07:26 UTC, literat commented on src/languages/cs.ts
> +          secondaryButtonMode !== SecondaryButtonMode.SHOW_SETTINGS
I think it will improve readability if there will be a named function like `isSecondaryButtonShown(secondaryButtonMode)` or something similar. This condition is the same in multiple files, so we can provide a function.

2022-04-21 12:22 UTC, OndraM commented on src/LmcCookieConsentManager.ts
>    const languages = {
I was unable to make this work, it seems not to be easy to call default export of a module by a string value.

For example this fails on `Uncaught TypeError: configCallback is not a function`.

2022-04-21 12:32 UTC, OndraM commented on src/languages/cs.ts
> +          secondaryButtonMode !== SecondaryButtonMode.SHOW_SETTINGS
Well, the logic is that this sentence should be added only if the "Open settings" button is not already shown as the secondary button. So its hard to find accurate name. (`isSecondaryButtonShown` would be misleading, there is always secondary button). What about `isSettingsButtonNotShown`?

2022-04-21 14:16 UTC, literat commented on src/LmcCookieConsentManager.ts
>    const languages = {
Never mind, it was only suggestion, maybe ```window[`config${capitalize(language)}`]()``` should work.

2022-04-26 08:56 UTC, OndraM commented on src/languages/cs.ts
> +          secondaryButtonMode !== SecondaryButtonMode.SHOW_SETTINGS
Ok, updated, have a look please.

2022-04-26 12:41 UTC, literat approved these changes

2022-04-28 12:10 UTC, merged