Feat: Introduce new design connected to Spirit design tokens #CCM-7
lmc-eu/cookie-consent-manager pull request #30
Opened 2021-11-02 00:58 UTC by adamkudrna

<img width="1450" alt="obrazek" src="https://user-images.githubusercontent.com/5614085/139769832-2fd161b3-931c-4e32-8ec8-f09be0dc6b47.png">
<img width="1450" alt="obrazek" src="https://user-images.githubusercontent.com/5614085/139769844-6817c5ab-2751-4022-8885-dc383be814cd.png">
<img width="838" alt="obrazek" src="https://user-images.githubusercontent.com/5614085/139769857-5b8f1ec9-42ed-4dd8-8237-748594c5f8d7.png">
<img width="838" alt="obrazek" src="https://user-images.githubusercontent.com/5614085/139769864-b68e62f0-c54d-4571-930d-c790450a917c.png">
<img width="612" alt="obrazek" src="https://user-images.githubusercontent.com/5614085/139769879-1c050644-f4c2-481b-a6b1-1dc27447b9da.png">
<img width="612" alt="obrazek" src="https://user-images.githubusercontent.com/5614085/139769884-ded13ce1-1279-459f-8d30-5ede7f0419a6.png">

2021-11-02 07:59 UTC, literat requested changes

2021-11-02 07:59 UTC, literat commented on package.json
> +    "prebuild": "rm -rf dist && mkdir -p dist/scss && cp package.json README.md src/LmcCookieConsentManager.scss dist/ && cp -r src/scss/* dist/scss/",
This is going to be so long. May I suggest to create some new scripts?

```json
"build:clean": "rm -rf dist && mkdir -p dist/scss",
"build:copy": "cp package.json README.md src/LmcCookieConsentManager.scss dist/ && cp -r src/scss/* dist/scss/"
"prebuild": "npm-run-all --serial build:clean build:copy"
""
```

2021-11-02 10:07 UTC, literat approved these changes

2021-11-02 10:11 UTC, crishpeen approved these changes

2021-11-02 11:11 UTC, OndraM commented on README.md
> +```
BTW this may be subject of change - we can by default load the css through the theme_css feature.

Lets discuss this css/spirit-related issues on Thursday.

2021-11-02 11:18 UTC, OndraM commented on README.md
> +```bash
```suggestion
```sh
```

(for consistency)

2021-11-02 11:21 UTC, OndraM requested changes

2021-11-02 11:21 UTC, OndraM commented on examples/index.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1" />
```suggestion
  <meta name="viewport" content="width=device-width, initial-scale=1">
```

> As it is a void element, the start tag must be present and the **end tag must not be present**.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta


(also for the other link/meta tags below and above)

2021-11-02 11:24 UTC, OndraM commented on package.json
> +    "@lmc-eu/spirit-design-tokens": "~0.4.0",
```suggestion
    "@lmc-eu/spirit-design-tokens": "^0.4.0",
```

https://developer.happyr.com/always-use-caret-instead-of-tilde

2021-11-02 13:37 UTC, adamkudrna commented on examples/index.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1" />
> 6. Then, if the element is one of the void elements, or if the element is a foreign element, then there **may be a single U+002F SOLIDUS character (/)**. This character has no effect on void elements, but on foreign elements it marks the start tag as self-closing.

https://html.spec.whatwg.org/multipage/syntax.html#start-tags

🤔

2021-11-02 13:43 UTC, adamkudrna commented on package.json
> +    "@lmc-eu/spirit-design-tokens": "~0.4.0",
I disagree. `0.x` versions mark an [early stage of development](https://semver.org/#spec-item-4) with breaking changes happening even during minor version bumps. Allowing upgrade to a higher minor version of `0.x` thus may break the app.

Once the referred package version is `>=1`, then it's time to change `~` to `^`.

2021-11-02 16:35 UTC, OndraM commented on examples/index.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1" />
> This character has no effect on void elements

Soo, why should we have something which has no effect? :)  Both is valid, thats true, but for consistency - we use `<br>`, `<hr>` etc. in html5, so why this should be an exception?

2021-11-02 16:59 UTC, OndraM commented on package.json
> +    "@lmc-eu/spirit-design-tokens": "~0.4.0",
> Allowing upgrade to a higher minor version of 0.x thus may break the app.

But `^0.4.0` does not allow this. It means `>=0.4.0  < 0.5.0`, so "do safe upgrades without BC". So in the pre-1.x version, the behavior is effectively the same as using tilde. However after 1.x, the caret `^` follows safe semver upgrades (unlike tilde, which behaves differently and `~1.2.3` won't upgrade to `1.3.0`) .

So exactly what you wrote is the reason why use caret, for both 0.x and 1.x+ versions, without a need to remember you should change it after 1.x.

https://github.com/npm/node-semver#caret-ranges-123-025-004
https://semver.npmjs.com/

2021-11-03 10:09 UTC, literat commented on package.json
> +    "@lmc-eu/spirit-design-tokens": "~0.4.0",
@OndraM @adamkudrna And what about to pin the version to exact match, eg. `"@lmc-eu/spirit-design-tokens": "0.4.0",` and let dependabot to take care of updates?

Everybody got the same version and breaking and other changes would be under control in separate PRs. And also there will be no arguing about tilda or caret ;-)

2021-11-04 13:27 UTC, adamkudrna commented on examples/index.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1" />
I've been always used to writing trailing `/` everywhere, `<br />` or `<hr />` being no exception. In React projects, ESlint gives me no other choice anyway.

Generally speaking, when there are more possible ways of syntax in a code, I prefer the one which is easier to read and understand, even if it means more writing. To me, trailing slash denotes a self-closing element, as opposed to elements with starting and ending tags, and I'm able to recognize it even without reading actual tag names.

2021-11-04 13:30 UTC, adamkudrna commented on package.json
> +    "@lmc-eu/spirit-design-tokens": "~0.4.0",
> So in the pre-1.x version, the behavior is effectively the same as using tilde.

Nice one, didn't know that!

2021-11-04 17:00 UTC, OndraM commented on examples/index.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1" />
Understand your point and read it carefully, but still don't agree its valid for this (eg. this is not XML like JSX). So I don't think there is any benefit in doing thing differently than what is currently the de-facto standard / mostly used. From quick research, the no-slash version is also the usual convention in LMC products. So having example with different conventions will not make it easier for anyone.

So let move on with this - and go with the short version and no closing tags please :)

2021-11-04 17:03 UTC, OndraM commented on examples/index.html
> +  <meta name="viewport" content="width=device-width, initial-scale=1" />
(Or maybe just don't spend time on this now and let it be 🎶 - I will do some more cleanups in #37, so I can do it altogether...)

2021-11-04 19:41 UTC, OndraM commented on README.md
> +the original plugin CSS has been loaded.
This complicates the ease of use a bit... 🤯

2021-11-04 19:44 UTC, OndraM requested changes
Remove all the `dist/` file changes pls :)

2021-11-04 19:57 UTC, adamkudrna commented on README.md
> +the original plugin CSS has been loaded.
You're fine when loading plugin's CSS via `<link>` in `<head>`. Things get a little bit more complicated with `themeCss` though — then you need to bundle the original CSS with your custom properties.

2021-11-04 20:45 UTC, adamkudrna commented on README.md
> +the original plugin CSS has been loaded.
Improved, see `fixup!`.

2021-11-05 08:27 UTC, OndraM approved these changes
LGTM, thanks! 👍

2021-11-05 09:26 UTC, literat approved these changes

2021-11-05 12:30 UTC, merged