Chore: Automatically replace package version in readme file to actual
lmc-eu/cookie-consent-manager pull request #33
Opened 2021-11-02 12:44 UTC by literat

2021-11-02 13:59 UTC, adamkudrna approved these changes

2021-11-02 17:29 UTC, OndraM requested changes
Maybe change the commit message: `actual` (skutečný, opravdový) -> `current` (současný, aktuální)

2021-11-02 17:29 UTC, OndraM commented on scripts/readme-replace-version.js
> +  to: `@v${packageJson.version}`,
```suggestion
  from: /(cookie-consent-manager@v)([0-9]\.[0-9]\.[0-9])/gm,
  to: `cookie-consent-manager@v${packageJson.version}`,
```

- `.` will match any character, thats probably not what we want
- I'd expand the matched part, to avoid any possible unintentional replacements.  Like if I write in readme: "Do not use v1.2.3, it is bad!", it will get replaced to current version :slightly_smiling_face:  . This is almost [real-world scenario](https://github.com/lmc-eu/cookie-consent-manager/pull/30/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R252).
- BTW is the `v`-prefix still [supposed to be there](https://github.com/lmc-eu/cookie-consent-manager/pull/36)?

2021-11-03 08:54 UTC, literat commented on scripts/readme-replace-version.js
> +  to: `@v${packageJson.version}`,
Thank you for you suggestion. I've just applied it.

About that `v` prefix on jsdelivr I think that this is on us what we want to use. I've tried both urls with `v` and without `v` and they are working.

- https://cdn.jsdelivr.net/npm/@lmc-eu/cookie-consent-manager@v0.3.0/init.js
- https://cdn.jsdelivr.net/npm/@lmc-eu/cookie-consent-manager@0.3.0/init.js

2021-11-03 08:55 UTC, literat commented on scripts/readme-replace-version.js
> +  to: `@v${packageJson.version}`,
But I think because we are tagging without `v` so we should also use urls. without `v`.

2021-11-03 08:57 UTC, OndraM commented on scripts/readme-replace-version.js
> +  to: `@v${packageJson.version}`,
+1 for omitting the v :)

2021-11-03 09:42 UTC, literat commented on scripts/readme-replace-version.js
> +  to: `@v${packageJson.version}`,
`v` ommitet and commit message changed.

2021-11-04 10:26 UTC, OndraM approved these changes
If you have a chance, please change the commit message as part of rebase :)

2021-11-04 10:30 UTC, literat commented
> If you have a chance, please change the commit message as part of rebase :)

The commit message has been changed already.

2021-11-04 10:46 UTC, merged