Chore: Switch from `sass` to `sass-embedded`
lmc-eu/cookie-consent-manager pull request #363
Opened 2024-10-21 11:45 UTC by literat

* @see: https://sass-lang.com/blog/embedded-sass-is-live/
* more performand
* modern API

2024-10-21 12:33 UTC, OndraM requested changes
I merged the previous PRs, could you please rebase?

2024-10-21 14:00 UTC, OndraM commented on package.json
> +    "sass-embedded": "^1.80.3",
Also pin the version please :)

2024-10-21 15:32 UTC, literat commented on package.json
> +    "sass-embedded": "^1.80.3",
Fixed.

2024-10-21 15:33 UTC, literat commented
> I merged the previous PRs, could you please rebase?

Rebased.

2024-10-22 12:36 UTC, OndraM approved these changes

2024-10-22 14:38 UTC, merged