Docs: Revamp examples #CCM-20
lmc-eu/cookie-consent-manager pull request #37
Opened 2021-11-02 17:46 UTC by OndraM

These are revamped examples - they were prepared for todays presentation, so not everything is as clean as it should. I welcome your suggestions - what examples add, whether the structure should be somehow changed etc.

It is based on bootstrap 5, as I needed something to make it quickly and good looking.

I set GitHub to deploy this branch here: https://lmc-eu.github.io/cookie-consent-manager/examples/

.. so that anyone can see the examples online right now, because the time is pressing us a bit.

2021-11-03 09:58 UTC, literat requested changes

2021-11-03 09:58 UTC, literat commented on examples/callbacks.html
> +    const element = document.getElementById('callback-' + id);
If you are using `const` you can also use template literals for string concatenation, eg.
```
`callback-${id}`
```

2021-11-03 09:58 UTC, literat commented on examples/callbacks.html
> +        onAccept: (cookie, cookieConsent) => { // any type of consent detected
I prefer to add comments above the function and not to an open bracket. Seems to me better for copy and formatting and reading the code (I see comment first and then function not opposite as here).

2021-11-03 09:58 UTC, literat commented on examples/callbacks.html
> +                <a href="" class="btn btn-warning" onclick="document.cookie = 'lmc_ccm=; Max-Age=0; path=/; domain=' + location.hostname;">
I think it would be better define this onClick as a named function and use it here. For better code readability I prefer something like `onclick="removeCookieAndReload()"`.

2021-11-03 09:58 UTC, literat commented on examples/configuration.html
> +                <a href="" class="btn btn-warning" onclick="document.cookie = 'lmc_ccm=; Max-Age=0; path=/; domain=' + location.hostname;">
This is the same as in `callbacks.html`. Please define a function or use external file where you store those functions. Keep it DRY.

2021-11-03 09:58 UTC, literat commented on examples/index.html
> +    const element = document.getElementById('consent-' + category);
You can use template literals.

2021-11-04 11:09 UTC, OndraM commented on examples/configuration.html
> +                <a href="" class="btn btn-warning" onclick="document.cookie = 'lmc_ccm=; Max-Age=0; path=/; domain=' + location.hostname;">
True, will do :) .This was done a bit in a hurry... :upside_down_face:

2021-11-04 17:44 UTC, OndraM commented on examples/callbacks.html
> +    const element = document.getElementById('callback-' + id);
This kinda reminded me PHP's curly braces variables in strings, which we are avoiding for like 10 years, all over again :upside_down_face:  . But if this is considered ok in ES, why not, I will change :)

2021-11-04 17:51 UTC, OndraM commented on examples/callbacks.html
> +        onAccept: (cookie, cookieConsent) => { // any type of consent detected
🤔 I just tried, but then it looks weird if the other "scalar" parameters have the comment inline... And it would be unusual and long to have it on the line before for them as well, imho :shrug:

```js
      {
        autodetectLang: false, // do not detect language from the browser
        defaultLang: 'en', // use 'en' language by default
        config: { // override default config of the underlying library, see https://github.com/orestbida/cookieconsent#all-available-options
          delay: 500, // show cookie consent banner after 500ms
          page_scripts: false, // disable third-party script management, see https://github.com/lmc-eu/cookie-consent-manager#third-party-scripts-loaded-via-script
        },
      }
```
vs
```js
      {
        // do not detect language from the browser
        autodetectLang: false,
        // use 'en' language by default
        defaultLang: 'en',
        // override default config of the underlying library, see https://github.com/orestbida/cookieconsent#all-available-options
        config: { 
          // show cookie consent banner after 500ms
          delay: 500, 
          // disable third-party script management, see https://github.com/lmc-eu/cookie-consent-manager#third-party-scripts-loaded-via-script
          page_scripts: false,
        },
      }
```

What do you think?

2021-11-04 17:54 UTC, OndraM commented on examples/configuration.html
> +                <a href="" class="btn btn-warning" onclick="document.cookie = 'lmc_ccm=; Max-Age=0; path=/; domain=' + location.hostname;">
Moved to external file, have a look :)

2021-11-04 17:54 UTC, OndraM commented on examples/index.html
> +    const element = document.getElementById('consent-' + category);
Done

2021-11-05 09:23 UTC, literat requested changes

2021-11-05 09:23 UTC, literat commented on examples/callbacks.html
> +        onAccept: (cookie, cookieConsent) => { // any type of consent detected
I've done quick research and clear to myself what visually bothers me. I have no problem with inline comments but those in curly braces are bad, I think.

Please see an eslint rule for that: https://eslint.org/docs/rules/no-inline-comments

So `autodetectLang: false, // do not detect language from the browser` is ok.

This is bad and comment should be above the function.
```
onAcceptAll: (cookie, cookieConsent) => { // consent for all cookies detected
          markCallbackCalled('onAcceptAll');
```

I am not sure about this
```
config: { // override default config of the underlying library, see https://github.com/orestbida/cookieconsent#all-available-options delay: 500, // show cookie consent banner after 500ms
```

I think that it is wrong and should be as like this
```
// override default config of the underlying library, see https://github.com/orestbida/cookieconsent#all-available-options
config: {
```

But I am not 100 % sure because it can be weird
```
      {
        autodetectLang: false, // do not detect language from the browser
        defaultLang: 'en', // use 'en' language by default
        // override default config of the underlying library, see https://github.com/orestbida/cookieconsent#all-available-options
        config: { 
          delay: 500, // show cookie consent banner after 500ms
          page_scripts: false,  // disable third-party script management, see https://github.com/lmc-eu/cookie-consent-manager#third-party-scripts-loaded-via-script
        },
      }

```

All three most used eslint configs (standard, recommended, airbnb) have this rule turned off (https://sqren.github.io/eslint-compare/). So maybe the problem is just in me :-)

2021-11-07 16:37 UTC, OndraM commented on examples/callbacks.html
> +        onAccept: (cookie, cookieConsent) => { // any type of consent detected
Yes, I'm conflicted exactly about the last example, which triggers OCD :-D . I did a quick search in node_modules and comment after opening curly braces is used quite often. However this is nothing important to me, we can change it if you want - though I'd prefer if this would be part of some LMC-wide eslint rules which we would just obey here, so that we don't have to decide this here. 🤷

2021-11-07 16:48 UTC, OndraM commented
Rebased to `main` and ready for final review 🚀

2021-11-08 16:57 UTC, literat commented on examples/callbacks.html
> +        onAccept: (cookie, cookieConsent) => { // any type of consent detected
Ook, let it be as is.

2021-11-08 17:27 UTC, literat approved these changes

2021-11-09 10:05 UTC, merged