Feat/ccm 25 text parametrisation
lmc-eu/cookie-consent-manager pull request #59
Opened 2021-11-12 15:21 UTC by literat

2021-11-12 15:36 UTC, OndraM commented
> Lastly, @OndraM should we rename uk config to ua? I am confused because uk is normally United Kingdom and Ukraine is ua.

I was confused as well, but ISO 3166 country code (which is "ua" for the country Ukraine) is different than [ISO 639 language code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) for the language Ukrainian ("uk"). 🤷

2021-11-12 15:41 UTC, literat commented
> I was confused as well, but ISO 3166 country code (which is "ua" for the country Ukraine) is different than [ISO 639 language code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) for the language Ukrainian ("uk"). 🤷

@OndraM Well, we should definitely extend our readme, because I've just notice that newly added languages are missing. And maybe add this information to separate section. Something like "Supported languages".

2021-11-12 15:42 UTC, OndraM commented
> > I was confused as well, but ISO 3166 country code (which is "ua" for the country Ukraine) is different than [ISO 639 language code](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) for the language Ukrainian ("uk"). shrug
> 
> @OndraM Well, we should definitely extend our readme, because I've just notice that newly added languages are missing. And maybe add this information to separate section. Something like "Supported languages".

True, I will update the readme.

2021-11-12 15:43 UTC, OndraM commented
(wrong button, sorry :facepalm: )

2021-11-12 15:44 UTC, literat commented
> (wrong button, sorry 🤦 )

:D I am happy that I am not the only one to whom this happens :D

2021-11-12 22:18 UTC, OndraM commented on src/languages/__tests__/cs.test.js
> +import { config } from '../cs';
Could this be somehow more DRY to not have exactly the same test eight times?

Its been a long time I worked with Jest, but in eg. PHPUnit I would for example create a common ancestor with the common logics of the test and make eight test classes which extends it. 

Or maybe even just one test class, which will test the functions in all the eight files.

2021-11-12 22:18 UTC, OndraM commented on src/utils.js
> +export const plural = (count, singular, plural) => (count === 1 ? singular : plural);
What about call it `pluralize`? This would sound as a more descriptive name to me.

2021-11-12 22:18 UTC, OndraM commented on src/utils.js
> +      return `${accumulator} ${and} ${string}`;
```suggestion
      return `${accumulator} ${and} ${string}`;
```
(replace ordinary space with no-break space character ` `)

2021-11-15 00:11 UTC, OndraM commented on src/languages/__tests__/cs.test.js
> +});
Proof of concept for table testing, so that all configs are checked using one test to DRY:

```suggestion
import { config as configCs } from '../cs';
import { config as configDe } from '../de';

describe.each([
  ['cs', configCs],
  ['de', configDe]
])('%s config', (language, config) => {
  it('should return localization object', () => {
    expect(config({companyNames: ['test1', 'test2', 'test3']})).toMatchSnapshot();
  });
})
```

2021-11-15 09:07 UTC, literat commented on src/utils.js
> +      return `${accumulator} ${and} ${string}`;
Fixed.

2021-11-15 09:07 UTC, literat commented on src/utils.js
> +export const plural = (count, singular, plural) => (count === 1 ? singular : plural);
Fixed.

2021-11-15 10:58 UTC, literat commented on src/languages/__tests__/cs.test.js
> +import { config } from '../cs';
Yeah, I know that this is something I should refactor. But I did not know if this concept of testing would be appropriate and if you would ok with it. 

I have refactored it using `jest-each`. But still, if you update translations in the future it would be also needed to update snapshots as well using `yarn test:unit -u`.

2021-11-15 10:58 UTC, literat commented on src/languages/__tests__/cs.test.js
> +});
Refactored.

2021-11-16 12:02 UTC, OndraM requested changes

2021-11-16 12:06 UTC, OndraM commented on src/languages/__tests__/langConfig.test.js
> +each([
BTW why you used `each([]).describe()` instead of `describe.each([])()` from [jest](https://jestjs.io/docs/api#1-describeeachtablename-fn-timeout)?

2021-11-18 09:52 UTC, literat commented on src/languages/__tests__/langConfig.test.js
> +each([
Good point, this is something new to me because when I started to use `jest-each` there was no native `.each` helper. Thanks. Refactored.

2021-11-18 09:56 UTC, literat commented on src/languages/cs.js
> +        extra.and,
Fixed.

2021-11-18 09:56 UTC, literat commented on src/languages/cs.js
> + * @param {array} [args.companyNames] - Array of strings with company names used to parametrized translations
Fixed.

2021-11-18 09:56 UTC, literat commented on src/LmcCookieConsentManager.js
> + * @param {array} [args.companyNames] - Array of strings with company names used to parametrized translations
Fixed

2021-11-18 09:56 UTC, literat commented on README.md
> +| `companyNames`| array | ['LMC']                           | Array of strings with company names used to parametrized translations. |
Fixed

2021-11-18 12:05 UTC, OndraM commented
Looks nice! So could you un-draft the PR (and rebase to `main`)?

2021-11-19 12:28 UTC, OndraM approved these changes
:shipit:

2021-11-19 14:16 UTC, merged