Docs: Do not use patch part in URL to update to bugfix versions automatically
lmc-eu/cookie-consent-manager pull request #61
Opened 2021-11-14 14:10 UTC by OndraM

[#CCM-29](https://jira.int.lmc.cz/browse/CCM-29)

2021-11-15 08:09 UTC, literat requested changes

2021-11-15 08:09 UTC, literat commented on scripts/readme-replace-version.js
> +const newVersion = packageJson.version.replace(/([0-9])\.([0-9])\.([0-9])/, '$1.$2');
Well, can also just `match` the prefered part and get first match as `.match(/([0-9])\.([0-9]/)[0]`. No need for match and replace.

And after this little refactor you can also add the regex into variable and use it on both places here, i think ;-)

2021-11-15 08:09 UTC, literat commented on README.md
> +<script defer src="https://cdn.jsdelivr.net/npm/@lmc-eu/cookie-consent-manager@0.5/init.js"></script>
Please, add a simple note/disclaimer here why we are using "latest" version. It should be clear to everyone but, you know, sometimes is everbody suprised with some version with unintenional bug in it.

2021-11-16 11:32 UTC, OndraM commented on scripts/readme-replace-version.js
> +const newVersion = packageJson.version.replace(/([0-9])\.([0-9])\.([0-9])/, '$1.$2');
Changed to match, but I'm not quite sure it is more readable :upside_down_face: : .

Also I don't think it will not be good to reuse the regexp below, as we are looking for different pattern and concatenating the regexp would make it less clear, IMHO.

2021-11-16 11:32 UTC, OndraM commented on README.md
> +<script defer src="https://cdn.jsdelivr.net/npm/@lmc-eu/cookie-consent-manager@0.5/init.js"></script>
Added, have a look.

2021-11-18 09:59 UTC, literat approved these changes

2021-11-18 10:21 UTC, merged