Feat: Generate and store consent UUID on accept
lmc-eu/cookie-consent-manager pull request #70
Opened 2021-11-17 21:54 UTC by OndraM

The next part of CCM-35 after #69.

I thought we would not need uuid library... However from what I've read regarding Math.random(), any uuid function based on it would mean high chance of collisions. And since the traffic this would have and necessity to have uuid really unique, this could be problematic.

2021-11-17 21:55 UTC, OndraM commented on src/LmcCookieConsentManager.js
> +        if (cookieConsent.get('data') === null || !('uuid' in cookieConsent.get('data'))) {
The second condition is for possibility someone will store something in the cookie as part of onAccept above, and we still need to generate and store the UUID.

2021-11-18 07:26 UTC, literat requested changes

2021-11-18 07:26 UTC, literat commented on src/LmcCookieConsentManager.js
> +import { v4 as uuidv4 } from 'uuid';
Please, consider use of `nanoid` instead of `uuid`. It is faster, smaller and uses better random number generator: https://github.com/ai/nanoid#comparison-with-uuid

2021-11-18 10:17 UTC, OndraM commented on src/LmcCookieConsentManager.js
> +import { v4 as uuidv4 } from 'uuid';
Nice, didn't know this library - replaced.

2021-11-18 10:33 UTC, literat commented on src/LmcCookieConsentManager.js
> +import { v4 as uuidv4 } from 'uuid';
I think we have a conversation about this already - https://lmccz.slack.com/archives/CU9D52MTK/p1625815872001000 ;-)

2021-11-18 10:35 UTC, literat requested changes

2021-11-18 10:35 UTC, literat commented on src/LmcCookieConsentManager.js
> +        if (cookieConsent.get('data') === null || !('uuid' in cookieConsent.get('data'))) {
Maybe little optimization but should't it `cookieConsent.get('data')` be in a variable? Because in that condition it is used twice.

2021-11-18 10:38 UTC, OndraM commented on src/LmcCookieConsentManager.js
> +        if (cookieConsent.get('data') === null || !('uuid' in cookieConsent.get('data'))) {
Ok, I thought it internally just returns the value, but it actually parses the json once again, so ok :upside_down_face:  , although it is really just a microoptimalization :)

2021-11-18 10:58 UTC, literat requested changes

2021-11-18 10:58 UTC, literat commented on src/LmcCookieConsentManager.js
> +            value: { serviceName: serviceName, uuid: nanoid() },
In a case when `cookieData` is not null but there is no `uuid` property you are replacing entire value object. Maybe it will be safer if you destructure old value into new one.

`value: { ...cookieData.value, serviceName: serviceName, uuid: nanoid() },`

But there is a problem with existence of property `value` on a `null`. 🤔

2021-11-18 11:01 UTC, OndraM commented on src/LmcCookieConsentManager.js
> +            value: { serviceName: serviceName, uuid: nanoid() },
> In a case when cookieData is not null but there is no uuid property you are replacing entire value object. 

Not really, see `mode: 'update'`. This [is handled](https://github.com/orestbida/cookieconsent/blob/master/src/cookieconsent.js#L1353-L1370) by the vanilla library and it should only update the given properties.

2021-11-18 11:19 UTC, literat commented on src/LmcCookieConsentManager.js
> +            value: { serviceName: serviceName, uuid: nanoid() },
Thanks, I did not notice.

2021-11-18 11:19 UTC, literat approved these changes

2021-11-18 11:31 UTC, OndraM commented
One more change - replace `uuid` which refers to the "Universally unique identifier" standard (we no longer use) with `uid` as more generic "user id"...

2021-11-18 13:41 UTC, literat approved these changes

2021-11-18 19:07 UTC, merged