Docs/improve font instructions
lmc-eu/cookie-consent-manager pull request #93
Opened 2021-11-26 18:37 UTC by adamkudrna

- Fix: Revert font family inheritance as it blocked font customization
- Feat: Let base font size be inherited from surrounding text
- Docs: Make clear that Inter font link is mandatory unless font family is customized
- Deps: Update Spirit Design Tokens

As a result:

- Font size should work normally even on sites that use 10px hack for easier calculations.
- Cookie consent UI is rendered with a sans-serif font until Inter web font is loaded.
- We make it clear that Inter font is mandatory unless font family is customized (either via Spirit or custom properties).

2021-11-28 09:53 UTC, OndraM requested changes

2021-11-28 09:53 UTC, OndraM commented on README.md
> +<summary>Make sure you have `node_modules` and path to your design tokens in your Sass include paths.</summary>
```suggestion
<summary>Make sure you have <code>node_modules</code> and path to your design tokens in your Sass include paths.</summary>
```

The markdown obviously does not work here 🤷

2021-11-28 09:53 UTC, OndraM commented on README.md
> +Change their values to match the design of your site, for example:
Maybe describe some theory of operation - how does it work in this scenario. That you must load the default css, and then use CSS variables to customize it.

2021-11-28 09:53 UTC, OndraM commented on README.md
> +   See below for [theme customization options](#theming).
As we discussed personally, maybe extract font-related information to step 4, so that the installation is more gradual. (1. npm install; 2. import js; 3. import css; 4. import font).

2021-11-30 11:28 UTC, OndraM commented on README.md
> +<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap">
I would shorten this whole block just to some sentence like:

```suggestion
If you used custom font like this, make sure you don't load the default Inter font and that you use `<link rel="preconnect" ...>` only to actually needed domains.
```

Because if you followed the new installation scenario, you would not came to the case when you first added the font and then you need to remove it. So this is imho a redundant and overly-detailed information.

Yes, loading the font is in the basic usage, but I see it as a quick information how does this work and how to get it quickly working, not as a full copy-paste code someone will put to production code, without reading the rest from the readme... 🤷

2021-11-30 11:28 UTC, OndraM approved these changes

2021-11-30 11:38 UTC, adamkudrna commented on README.md
> +<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap">
It's not clear to me even as an author of the docs. But if you think that _Basic usage_ is more about how it works and not about how people should actually use it, let's go ahead and simplify it as you suggest.

2021-11-30 11:49 UTC, OndraM commented on README.md
> +<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap">
> It's not clear to me even as an author of the docs.

:smile:  :thinking: 


Well, this was just a note. For me has this part opposite meaning, it would confuse me: "Why is it describing in such detailed way how to remove something I didn't even add?"

But if you think this would help you if you would be in the role of someone implementing this, just decide yourselves whether keep this or not. Maybe at least reverse order of the sentence, to begin with "If you initially followed the [basic](#basic-usage) instructions, ...". So that you know whether it is for you relevant or not.

2021-11-30 19:15 UTC, adamkudrna commented on README.md
> +<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap">
I changed it as you originally suggested. Let's wait and see what developers say once they start using it.

2021-11-30 19:15 UTC, merged