Docs/custom theme demo
lmc-eu/cookie-consent-manager pull request #94
Opened 2021-11-26 21:20 UTC by adamkudrna

![Snímek obrazovky 2021-11-26 v 22 18 54](https://user-images.githubusercontent.com/5614085/143655688-4569473a-7592-44e1-98ca-095b98171fb5.png)
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/5614085/143655737-77ab49c3-f6a4-47e9-a3cc-a735534934ba.png">

2021-11-28 10:11 UTC, OndraM requested changes
👍 Nice to see the customization example!

2021-11-28 10:11 UTC, OndraM commented on examples/theming.html
> +        .ikea-theme {
🤔 Maybe do not use this name to avoid trademark issues 🤷

2021-11-30 10:30 UTC, literat approved these changes

2021-11-30 11:30 UTC, OndraM approved these changes

2021-11-30 11:42 UTC, OndraM commented on examples/theming.html
> +                    Toggle custom theme
While the dark mode icon is state-full, this one is not. Also because of this, it was not obvious to me these two things could be combined (custom theme + dark mode). 

Maybe the best UI element for these two things would be something like checkbox or some on-off switch.

2021-11-30 11:46 UTC, adamkudrna commented on examples/theming.html
> +                    Toggle custom theme
I've tried switch and it seemed too small me… I'll give it another try.

2021-11-30 15:40 UTC, adamkudrna commented on examples/theming.html
> +                    Toggle custom theme
We agreed on moving this to a standalone PR so this one is not blocked.

2021-11-30 18:51 UTC, adamkudrna commented on README.md
> +| `--lmcccm-btn-border-style`           | Button border style                                     |
I added these two properties so button borders can be adjusted.

2021-11-30 19:03 UTC, merged